<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="RoleFunEdit.aspx.cs" Inherits="MyQuery.Web.Sys.RoleFunEdit" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>角色功能编辑</title>
    <style type="text/css">
        body
        {
            margin: 0px;
            padding: 0px;
            background-color: #dfe8f6;
        }
        .editblock
        {
            text-align: left;
            background-repeat: repeat-x;
            background-color: #dfe8f6;
            border: 1px solid #96c1e1;
        }
        td,th
        {
            height: 20px;
            font-size: 12px;
        }
        .operation
        {
            padding: 4px;
            color: #367cad;
            text-align: right;
            color: #367cad;
            margin: 0px 0px 3px 0px;
        }
        .operation input
        {
            background-image: url(../Images/button.gif);
            background-repeat: repeat-x;
            background-position: left top;
            border: 1px solid #9ebae1;
            line-height: 20px;
            height: 20px;
            color: #000000;
            cursor: pointer;
            background-color: #ffffff;
            margin-left: 3px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div class="editblock" style="width: 98%; margin-top: 10px;">
        <table border="0" cellpadding="0" cellspacing="0" width="100%">
            <colgroup>
                <col style="width: 100px;" />
                <col />
            </colgroup>
            <tr>
                <th>
                    &nbsp;&nbsp;角色名称：
                </th>
                <td >
                    <asp:Label ID="lblRoleName" runat="server"></asp:Label>
                </td>
            </tr>
            <tr>
                <td colspan="2" valign="top">
                    <div id="divFunctions" runat="server" style="width: 98%; height: 500px; overflow: auto; vertical-align: top">
                        <asp:TreeView ID="tvFunctions" runat="server" ExpandDepth="0" ShowCheckBoxes="All"
                            AutoGenerateDataBindings="false" EnableTheming="false" EnableClientScript="false"
                            PopulateNodesFromClient="False" ShowLines="True" NodeWrap="True">
                        </asp:TreeView>
                    </div>
                </td>
            </tr>
        </table>
    </div>
    <div class="operation" style="width: 90%;">
        <asp:Button ID="btnSave" runat="server" Text="提 交" CssClass="input_button" OnClick="btnSave_Click" />
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="button" value="取 消"  onclick="window.close()" />
    </div>
    </form>
</body>
</html>
